In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.formula.api as smf

import pickle
import os

### Question 2
* Do customer service calls signal frustration or engagement?
Churn climbs with call volume, from about 65% for customers with zero calls to over 90% for those with 5+. That raises a business question: at how many calls should a customer be escalated to retention outreach? You could also test whether calls matter on their own or just overlap with inactivity.

In [3]:
dataset = '../data/customer_churn_clean.csv'
result_dir = '../result'

df = pd.read_csv(dataset)
df.head()

,Unnamed: 0,customer_id,gender,region,subscription_plan,payment_method,age,days_since_last_login,customer_service_calls,monthly_spend,churn
0,0,10001,Male,East,Basic,PayPal,27.0,27,1.0,61.08,0
1,1,10002,NaN,West,Pro,PayPal,55.0,146,2.0,73.09,0
2,2,10003,Female,West,Pro,E-Wallet,NaN,147,2.0,116.30,1
3,3,10004,Female,South,Basic,Credit Card,NaN,34,1.0,0.58,1
4,4,10005,Male,North,Basic,Crypto,30.0,146,3.0,46.35,1

#### Analysis Variables
* customer_service_calls
    - total number of 
* days_since_last_login
    - time (in days) since last login
* churn
    - target variable; 
        - 1 = churned
        - 2 = retained

In [10]:
calls_churn = df[['customer_service_calls','days_since_last_login','churn']].dropna()
cc_rate = calls_churn[['customer_service_calls','churn']].groupby(['customer_service_calls']).agg(['mean','count'])
cc_rate

                           churn
                            mean count
customer_service_calls
0.0                     0.654685  1697
1.0                     0.723470  2893
2.0                     0.779255  2632
3.0                     0.835710  1613
4.0                     0.863329   739
5.0                     0.927536   276
6.0                     0.935065    77
7.0                     1.000000    19
8.0                     1.000000     3
9.0                     1.000000     1